name: Daily Python Script

on:
  schedule:
    - cron: '0 17 * * *'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set environment variable
      run: |
        echo "Setting API_KEY environment variable"
        echo "::set-env name=API_KEY::${{ secrets.API_KEY }}"
        
    - name: Run Python Script
      run: python global_quote.py
