name: Daily Python Script

on:
  schedule:
    - cron: '45 18 * * *'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variable
        run: |
          echo "Setting API_KEY environment variable"
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

      - name: Run Python Script
        env:
          API_KEY: ${{ env.API_KEY }}
        run: python global_quote.py
