name: Daily Python Script

on:
  schedule:
    - cron: '6 21 * * *' 

jobs:
  build:
    runs-on: ubuntu-latest  # change the OS to Ubuntu
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt  # install dependencies using Python 3.10
      
      - name: Run Python Script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python global_quote.py output/df_final.xlsx
